name: Preview Firebase Hosting

on: pull_request

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build-and-preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - run: npm install
      - run: npm run build
        env:
          VITE_FIREBASE_API_KEY: "AIzaSyDj9w8tjTqYubxGc3oOEoXAvlX5J70aQPU"
          VITE_FIREBASE_AUTH_DOMAIN: "processo-360-ia.firebaseapp.com"
          VITE_FIREBASE_PROJECT_ID: "processo-360-ia"
          VITE_FIREBASE_STORAGE_BUCKET: "processo-360-ia.firebasestorage.app"
          VITE_FIREBASE_MESSAGING_SENDER_ID: "685012306915"
          VITE_FIREBASE_APP_ID: "1:685012306915:web:e9c441be57f15b41ee6ed6"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROCESSO_360_IA }}
          projectId: processo-360-ia
